@base_url=http://localhost:3000

@taks_id=c1ed2815-ae54-4dea-bf3d-a6c4b581e048

###

# @name create-task
POST {{base_url}}/tasks
Content-Type: application/json

{
    "title": "Fazer algo",
    "description": "Tenho que fazer algo"
}

###

# @name delete-task
DELETE {{base_url}}/tasks/{{taks_id}}

###

# @name list-tasks
GET {{base_url}}/tasks?title=hello

###

# @name update-task
PUT {{base_url}}/tasks/{{taks_id}}
Content-Type: application/json

{
    "title": "Fazer algo teste teste teste teste",
    "description": "Tenho que fazer algo teste"
}

###

# @name complete-task
PATCH {{base_url}}/tasks/{{taks_id}}/complete
