@base_url=http://localhost:3000

@taks_id=c2eef878-2ba8-4abd-a59a-9f788e22df2a

###

# @name create-task
POST {{base_url}}/tasks
Content-Type: application/json

{
    "title": "Mais coisas",
    "description": "teste"
}

###

# @name delete-task
DELETE {{base_url}}/tasks/{{taks_id}}

###

# @name list-tasks
GET {{base_url}}/tasks

###

# @name update-task
PUT {{base_url}}/tasks/{{taks_id}}
Content-Type: application/json

{
    "title": "Fazer algo teste teste teste teste",
    "description": "Tenho que fazer algo teste"
}

###

# @name complete-task
PATCH {{base_url}}/tasks/{{taks_id}}/complete
